Front-end/Controllers/AdminController.cs
using GestiuneFilme.Domain.Abstract;
using GestiuneFilme.Domain.Entitities;
using GestiuneFilme.WebUI.Models;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using System.Web.Mvc;


namespace GestiuneFilme.WebUI.Controllers
{
    [Authorize(Users = "MihaiV, SaraP")]
    public class AdminController : Controller
    {
        private IFilmRepository repositoryFilm;
        private IUserRepository repositoryUser;
        int PageSize = 3;
        Observable observableFilm;
        List<User> users;

        public AdminController(IFilmRepository repoFilm, IUserRepository repoUser)
        {
            repositoryFilm = repoFilm;
            repositoryUser = repoUser;
        }
        public ActionResult Index()
        {
            return View(repositoryFilm.Films);
        }

        public ViewResult Create()
        {
            return View(new Film());
        }
        [HttpPost]
        public ActionResult Create(Film film, HttpPostedFileBase image1)
        {

        
            if (ModelState.IsValid)
            {
                if (image1 != null)
                {
                    film.imageFilm = new byte[image1.ContentLength];
                    image1.InputStream.Read(film.imageFilm, 0, image1.ContentLength);
                }
    
                repositoryFilm.SaveFilm(film);
        
                if (film.id != -1)
                {
                    
                    observableFilm = new Film();
                    users = repositoryUser.Users.Where(r => r.rol == "angajat").ToList();
                    foreach (Observer o in users)
                        observableFilm.attachObserver(o);

                    observableFilm.notifyObserver(film.titlu, "adaugat", users);

                   

                    TempData["message"] = string.Format("{0} has been saved", film.titlu);
                }
                else
                { 
                    TempData["message"] = string.Format("{0} has not been saved", film.titlu);
                }
                return RedirectToAction("Index");
            }
            else
            {
                return View(film);
            }
        }
        public ViewResult Edit(int id)
        {
            Film film = repositoryFilm.Films.FirstOrDefault(f => f.id == id);

            return View(film);
        }

        [HttpPost]
        public ActionResult Edit(Film film)
        {
            if (ModelState.IsValid)
            {
                repositoryFilm.SaveFilm(film);
                if (film.id != -1)
                {
                    observableFilm = new Film();
                    users = repositoryUser.Users.Where(r => r.rol == "angajat").ToList();

                    foreach (Observer o in users)
                        observableFilm.attachObserver(o);

                    observableFilm.notifyObserver(film.titlu, "editat", users);
                    TempData["message"] = string.Format("{0} has been saved", film.titlu);
                }
                else
                {
                    TempData["message"] = string.Format("{0} has not been saved", film.titlu);
                }
                return RedirectToAction("Index");
            }
            else
            {
                return View(film);
            }
        }

        [HttpPost]
        public ActionResult Delete(int id)
        {
            Film deletedFilm = repositoryFilm.DeleteFilm(id);
            if (deletedFilm != null)
            {
                observableFilm = new Film();
                users = repositoryUser.Users.Where(r => r.rol == "angajat").ToList();

                foreach (Observer o in users)
                    observableFilm.attachObserver(o);

                    observableFilm.notifyObserver(deletedFilm.titlu, "sters", users);

                TempData["message"] = string.Format("{0} was deleted", deletedFilm.titlu);
            }
            return RedirectToAction("Index");
        }

        public ViewResult ListFilme(int page = 1)
        {

            FilmsListViewModel model = new FilmsListViewModel
            {
                Films = repositoryFilm.Films
                        .OrderBy(f => f.id)
                        .Skip((page - 1) * PageSize)
                        .Take(PageSize),
                PagingInfo = new PagingInfo
                {
                    CurrentPage = page,
                    ItemsPerPage = PageSize,
                    TotalItems = repositoryFilm.Films.Count()
                }
            };

            return View(model);
        }

        //Creare Angajat
        public ActionResult IndexAngajat()
        {
            return View(repositoryUser.Users.Where(u => u.rol == "angajat").OrderBy(u => u.nume));
        }

        public ViewResult CreateAngajat()
        {
            return View(new User());
        }
        [HttpPost]
        public ActionResult CreateAngajat(User user)
        {
            if (ModelState.IsValid)
            {
                repositoryUser.SaveUser(user);
                if (user.rol != "bad")
                {
                    TempData["message"] = string.Format("{0} has been saved", user.nume);
                }

                else
                {
                    TempData["message"] = string.Format("{0} has not been saved", user.nume);

                }

                return RedirectToAction("IndexAngajat");
            }
            else
            {
                return View(user);
            }
        }


    }
}

Front-end/Controllers/ExportController.cs
using GestiuneFilme.Domain.Abstract;
using GestiuneFilme.Domain.Concrete;
using GestiuneFilme.Domain.Entitities;
using GestiuneFilme.WebUI.Models;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace GestiuneFilme.WebUI.Controllers
{
    [Authorize]
    public class ExportController : Controller
    {
        // GET: Export
        private IFilmRepository repositoryFilm;
        private IBiletRepository repositoryBilet;


        public ExportController(IFilmRepository repoFilm, IBiletRepository repoBilet)
        {
            repositoryFilm = repoFilm;
            repositoryBilet = repoBilet;
        }



        public ActionResult Download(string titlu, string exportType)
        {

            Exporter exporter = ExportFactory.chooseType(exportType);

            List<Bilet> bilete = repositoryBilet.Bilete.Where(b => b.film == titlu).ToList();


            return File(exporter.exportFilms(bilete), "text/plain", "file.txt");

        }
    }
}

Front-end/Views/Admin/Create.cshtml
@model GestiuneFilme.Domain.Entitities.Film

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h2>Add</h2>


@using (Html.BeginForm("Create", "Admin", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">
    <h4>Film</h4>
    <hr />
    @Html.ValidationSummary(true)

    <div class="form-group">
        @Html.LabelFor(model => model.titlu, new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.titlu)
            @Html.ValidationMessageFor(model => model.titlu)
        </div>
    </div>


    <div class="form-group">
        @Html.LabelFor(model => model.regia, new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.regia)
            @Html.ValidationMessageFor(model => model.regia)
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.distributia, new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.distributia)
            @Html.ValidationMessageFor(model => model.distributia)
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.numarBilete, new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.numarBilete)
            @Html.ValidationMessageFor(model => model.numarBilete)
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.dataPremiera, new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.dataPremiera)
            @Html.ValidationMessageFor(model => model.dataPremiera)
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.dataDifuzare, new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.dataDifuzare)
            @Html.ValidationMessageFor(model => model.dataDifuzare)
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.imageFilm, new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            <input type="file" name="image1" />
           
        </div>
    </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Adauga" class="btn btn-default" />
            </div>
        </div>
    </div>
    }

    <div>
        @Html.ActionLink("Inapoi la lista", "Index", null,
                             new { @class = "btn btn-success" })


    </div>

Front-end/Views/Admin/CreateAngajat.cshtml
@model GestiuneFilme.Domain.Entitities.User

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h2>Add</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Angajati</h4>
        <hr />
        @Html.ValidationSummary(true)

        <div class="form-group">
            @Html.LabelFor(model => model.nume, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.nume)
                @Html.ValidationMessageFor(model => model.nume)
            </div>
        </div>


        <div class="form-group">
            @Html.LabelFor(model => model.username, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.username)
                @Html.ValidationMessageFor(model => model.username)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.parola, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.parola)
                @Html.ValidationMessageFor(model => model.parola)
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Adauga" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Inapoi la lista", "IndexAngajat", null,
                             new { @class = "btn btn-success" })


</div>

Front-end/Views/Admin/Edit.cshtml
@model GestiuneFilme.Domain.Entitities.Film

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">
    <h4>Film</h4>
    <hr />
    @Html.ValidationSummary(true)
    @Html.HiddenFor(model => model.id)

    <div class="form-group">
        @Html.LabelFor(model => model.titlu, new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.titlu)
            @Html.ValidationMessageFor(model => model.titlu)
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.regia, new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.regia)
            @Html.ValidationMessageFor(model => model.regia)
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.distributia, new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.distributia)
            @Html.ValidationMessageFor(model => model.distributia)
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.numarBilete, new { @class = "control-label col-md-2" })
        <div class="col-md-10">

            @Html.EditorFor(model => model.numarBilete)
            @Html.ValidationMessageFor(model => model.numarBilete)
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.dataPremiera, new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.dataPremiera, new { htmlAttributes = new { @class = "datepicker" } })

            @Html.ValidationMessageFor(model => model.dataPremiera)
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.dataDifuzare, new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.dataDifuzare,  new { htmlAttributes = new { @class = "datepicker" } })
            @Html.ValidationMessageFor(model => model.dataDifuzare)
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Editeaza" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Inapoi la lista", "Index", null,
                 new { @class = "btn btn-success" })
</div>

Front-end/Views/Admin/Index.cshtml
@model IEnumerable<GestiuneFilme.Domain.Entitities.Film>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<div class="panel panel-default">
    <div class="panel-heading">
        <div>All Films</div>
    </div>
    <div class="panel-body">
        <table class="table table-striped table-condensed table-bordered">
            <tr>
                <th class="text-center">Film</th>
                <th class="text-center">Regia</th>
                <th class="text-center">Distributia</th>
                <th class="text-center">NumarBilete</th>
                <th class="text-center">DataPremiera</th>
                <th class="text-center">DataDifuzare</th>
                <th class="text-center">Delete Film</th>
                <th class="text-center">Export Json</th>
                <th class="text-center">Export CSV</th>


            </tr>
            @foreach (var item in Model)
            {
            <tr>
                <td class="text-center">
                    @Html.ActionLink(item.titlu, "Edit", new { item.id })
                </td>
                <td class="text-center">@item.regia</td>
                <td class="text-center">@item.distributia</td>
                <td class="text-center">@item.numarBilete.ToString()</td>
                <td class="text-center">@item.dataPremiera.Date.ToString("d")</td>
                <td class="text-center">@item.dataDifuzare.Date.ToString("d")</td>


                <td class="text-center">
                    @using (Html.BeginForm("Delete", "Admin"))
        {
            @Html.Hidden("id", item.id)
            <input type="submit"
                   class="btn btn-default btn-xs"
                   value="Delete" />
}


                </td>
                <td class="text-center">
                    @using (Html.BeginForm("Download", "Export", new { item.titlu, exportType = "JSON" }))
                    {
                @Html.Hidden("id", item.id)
                 <input type="submit"
                       class="btn btn-default btn-xs"
                       value="Export JSON" />
}


                </td>
                <td class="text-center">
                    @using (Html.BeginForm("Download", "Export", new { item.titlu , exportType = "CSV"}))
                    {
            @Html.Hidden("id", item.id)
            
             <input type="submit"
                   class="btn btn-default btn-xs"
                   value="Export CSV" />
}
                </td>



            </tr>
            }
        </table>
    </div>
    <div class="panel-footer">
        @Html.ActionLink("Adauga Film", "Create", null,
                  new { @class = "btn btn-default" })
    </div>
</div>

Front-end/Views/Admin/IndexAngajat.cshtml
@model IEnumerable<GestiuneFilme.Domain.Entitities.User>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<div class="panel panel-default">
    <div class="panel-heading">
        <div>All Employees</div>
    </div>
    <div class="panel-body">
        <table class="table table-striped table-condensed table-bordered">
            <tr>
                <th class="text-center">Nume</th>
                <th class="text-center">Username</th>
                <th class="text-center">Parola</th>

            </tr>
            @foreach (var item in Model)
            {
                <tr>
    
                    <td class="text-center">@item.nume</td>
                    <td class="text-center">@item.username</td>
                    <td class="text-center">@item.parola</td>
          
                </tr>
            }
        </table>
    </div>
    <div class="panel-footer">
        @Html.ActionLink("Adauga Angajat", "CreateAngajat", null,
                       new { @class = "btn btn-default" })
    </div>
</div>

Front-end/Views/Admin/ListFilme.cshtml
@model GestiuneFilme.WebUI.Models.FilmsListViewModel


@{
    ViewBag.Title = "ListFilme";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<br>

<br>
<div class="col-lg-3">
    <p style="padding-left: 20%">
@Html.ActionLink("Operatii pe filme", "Index", "Admin",
                                   new { @class = "btn-lg btn-success pull-left" })
        </p>
<br>
<br>
<br>
<br>
    <p style="padding-left:20%">
@Html.ActionLink("Adauga Angajat", "IndexAngajat", "Admin",
                                  new { @class = "btn-lg btn-success pull-left" })
       </p>
    </div>
<div class="col-lg-7">


    @foreach (var f in Model.Films)
    {
        @Html.Partial("FilmPartial", f)

    }
    <div class="btn-group pull-right">

        @Html.PageLinks(Model.PagingInfo, x => Url.Action("ListFilme", new { page = x }))

    </div>
</div>