Front-end/Controllers/AdminController.cs
using GestiuneFilme.Domain.Abstract;
using GestiuneFilme.Domain.Entitities;
using GestiuneFilme.WebUI.Models;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using System.Web.Mvc;


namespace GestiuneFilme.WebUI.Controllers
{
    [Authorize(Users = "MihaiV, SaraP")]
    public class AdminController : Controller
    {
        private IFilmRepository repositoryFilm;
        private IUserRepository repositoryUser;
        int PageSize = 3;
        Observable observableFilm;
        List<User> users;

        public AdminController(IFilmRepository repoFilm, IUserRepository repoUser)
        {
            repositoryFilm = repoFilm;
            repositoryUser = repoUser;
        }
        public ActionResult Index()
        {
            return View(repositoryFilm.Films);
        }

        public ViewResult Create()
        {
            return View(new Film());
        }
        [HttpPost]
        public ActionResult Create(Film film, HttpPostedFileBase image1)
        {

        
            if (ModelState.IsValid)
            {
                if (image1 != null)
                {
                    film.imageFilm = new byte[image1.ContentLength];
                    image1.InputStream.Read(film.imageFilm, 0, image1.ContentLength);
                }
    
                repositoryFilm.SaveFilm(film);
        
                if (film.id != -1)
                {
                    
                    observableFilm = new Film();
                    users = repositoryUser.Users.Where(r => r.rol == "angajat").ToList();
                    foreach (Observer o in users)
                        observableFilm.attachObserver(o);

                    observableFilm.notifyObserver(film.titlu, "adaugat", users);

                   

                    TempData["message"] = string.Format("{0} has been saved", film.titlu);
                }
                else
                { 
                    TempData["message"] = string.Format("{0} has not been saved", film.titlu);
                }
                return RedirectToAction("Index");
            }
            else
            {
                return View(film);
            }
        }
        public ViewResult Edit(int id)
        {
            Film film = repositoryFilm.Films.FirstOrDefault(f => f.id == id);

            return View(film);
        }

        [HttpPost]
        public ActionResult Edit(Film film)
        {
            if (ModelState.IsValid)
            {
                repositoryFilm.SaveFilm(film);
                if (film.id != -1)
                {
                    observableFilm = new Film();
                    users = repositoryUser.Users.Where(r => r.rol == "angajat").ToList();

                    foreach (Observer o in users)
                        observableFilm.attachObserver(o);

                    observableFilm.notifyObserver(film.titlu, "editat", users);
                    TempData["message"] = string.Format("{0} has been saved", film.titlu);
                }
                else
                {
                    TempData["message"] = string.Format("{0} has not been saved", film.titlu);
                }
                return RedirectToAction("Index");
            }
            else
            {
                return View(film);
            }
        }

        [HttpPost]
        public ActionResult Delete(int id)
        {
            Film deletedFilm = repositoryFilm.DeleteFilm(id);
            if (deletedFilm != null)
            {
                observableFilm = new Film();
                users = repositoryUser.Users.Where(r => r.rol == "angajat").ToList();

                foreach (Observer o in users)
                    observableFilm.attachObserver(o);

                    observableFilm.notifyObserver(deletedFilm.titlu, "sters", users);

                TempData["message"] = string.Format("{0} was deleted", deletedFilm.titlu);
            }
            return RedirectToAction("Index");
        }

        public ViewResult ListFilme(int page = 1)
        {

            FilmsListViewModel model = new FilmsListViewModel
            {
                Films = repositoryFilm.Films
                        .OrderBy(f => f.id)
                        .Skip((page - 1) * PageSize)
                        .Take(PageSize),
                PagingInfo = new PagingInfo
                {
                    CurrentPage = page,
                    ItemsPerPage = PageSize,
                    TotalItems = repositoryFilm.Films.Count()
                }
            };

            return View(model);
        }

        //Creare Angajat
        public ActionResult IndexAngajat()
        {
            return View(repositoryUser.Users.Where(u => u.rol == "angajat").OrderBy(u => u.nume));
        }

        public ViewResult CreateAngajat()
        {
            return View(new User());
        }
        [HttpPost]
        public ActionResult CreateAngajat(User user)
        {
            if (ModelState.IsValid)
            {
                repositoryUser.SaveUser(user);
                if (user.rol != "bad")
                {
                    TempData["message"] = string.Format("{0} has been saved", user.nume);
                }

                else
                {
                    TempData["message"] = string.Format("{0} has not been saved", user.nume);

                }

                return RedirectToAction("IndexAngajat");
            }
            else
            {
                return View(user);
            }
        }


    }
}

Front-end/Controllers/AngajatController.cs
using GestiuneFilme.Domain.Abstract;
using GestiuneFilme.Domain.Entitities;
using GestiuneFilme.WebUI.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;

namespace GestiuneFilme.WebUI.Controllers
{
    [Authorize]
    public class AngajatController : Controller
    {

        private IBiletRepository repository;
        int PageSize = 3;
        public AngajatController(IBiletRepository repo)
        {
            repository = repo;
        }
        public ActionResult Index()
        {
            return View(repository.Bilete);
        }

        public ViewResult Create()
        {
            return View(new Bilet());
        }
        [HttpPost]
        public ActionResult Create(Bilet bilet)
        {
            if (ModelState.IsValid)
            {
                repository.SaveBilet(bilet);
                if (bilet.bileteCumparate == -1)
                {
                    TempData["message"] = string.Format("Rezervarea filmului {0} nu a avut loc cu succes", bilet.film);
                }
                else if(bilet.bileteCumparate == 0)
                {
                    TempData["message"] = string.Format("Data filmului {0} nu este corecta", bilet.film);

                }
                else
                {
                    TempData["message"] = string.Format("Rezervarea filmului {0} a avut loc cu succes", bilet.film);

                }
                return RedirectToAction("Create");
            }
            else
            {
                return View(bilet);
            }
        }
    


        public ViewResult ListBilete(int page = 1)
        {

            BileteListViewModel model = new BileteListViewModel
            {
                Bilete = repository.Bilete
                        .OrderBy(f => f.id)
                        .Skip((page - 1) * PageSize)
                        .Take(PageSize),
                PagingInfo = new PagingInfo
                {
                    CurrentPage = page,
                    ItemsPerPage = PageSize,
                    TotalItems = repository.Bilete.Count()
                }
            };

            return View(model);
        }










    }
}

Front-end/Controllers/CumparatorController.cs
using GestiuneFilme.Domain.Abstract;
using GestiuneFilme.Domain.Entitities;
using GestiuneFilme.WebUI.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace GestiuneFilme.WebUI.Controllers
{
    public class CumparatorController : Controller
    {

        private IFilmRepository repositoryFilm;
        private IBiletRepository repositoryBilet;
        int PageSize = 3;

        public CumparatorController(IFilmRepository repoFilm, IBiletRepository repoBilet)
        {
            repositoryFilm = repoFilm;
            repositoryBilet = repoBilet;
        }

        public ViewResult RezervareBilete()
        {
            return View(new Bilet());
        }
        [HttpPost]
        public ActionResult RezervareBilete(Bilet bilet, string titluFilm)
        {
            if (ModelState.IsValid)
            {
                repositoryBilet.SaveBilet(bilet);
                if (bilet.bileteCumparate == -1)
                {
                    TempData["message"] = string.Format("Rezervarea filmului {0} nu a avut loc cu succes", bilet.film);
                }
                else if (bilet.bileteCumparate == 0)
                {
                    TempData["message"] = string.Format("Data filmului {0} nu este corecta", bilet.film);

                }
                else
                {
                    TempData["message"] = string.Format("Rezervarea filmului {0} a avut loc cu succes", bilet.film);

                }
                return RedirectToAction("RezervareBilete");
            }
            else
            {

                FilmsListViewModel model = new FilmsListViewModel
                {
                    Films = repositoryFilm.Films
                       .Where(f => f.titlu == titluFilm)
                 };

                return View(Tuple.Create(bilet, model));
            }
        }

        public ActionResult Search(String titluFilm)
        {
            int page = 1;
            FilmsListViewModel model;
            if (titluFilm != "")
            {
                model = new FilmsListViewModel
                {
                    Films = repositoryFilm.Films
                        .Where(f => f.titlu.Contains(titluFilm))
                        .Skip((page - 1) * PageSize)
                        .Take(PageSize),
                    PagingInfo = new PagingInfo
                    {
                        CurrentPage = page,
                        ItemsPerPage = PageSize,
                        TotalItems = repositoryFilm.Films.Count()
                    }
                };

            }
            else
            {
                model = new FilmsListViewModel
                {
                    Films = repositoryFilm.Films
                       .OrderBy(f => f.id)
                       .Skip((page - 1) * PageSize)
                       .Take(PageSize),
                    PagingInfo = new PagingInfo
                    {
                        CurrentPage = page,
                        ItemsPerPage = PageSize,
                        TotalItems = repositoryFilm.Films.Count()
                    }
                };


            }
            return View(model);
        }


        public ViewResult ListFilme(int page = 1)
        {

            FilmsListViewModel model = new FilmsListViewModel
            {
                Films = repositoryFilm.Films
                        .OrderBy(f => f.id)
                        .Skip((page - 1) * PageSize)
                        .Take(PageSize),
                PagingInfo = new PagingInfo
                {
                    CurrentPage = page,
                    ItemsPerPage = PageSize,
                    TotalItems = repositoryFilm.Films.Count()
                }
            };

            return View(model);
        }
    }
}

Front-end/Views/Shared/BiletPartial.cshtml
@model GestiuneFilme.Domain.Entitities.Bilet

<div class="well">
    <h3><strong> @Model.film </strong> </h3>
    <h4>Loc: @Model.loc</h4>
    <h4>Rand: @Model.rand</h4>
    <h4>Numar Bilete: @Model.bileteCumparate</h4>
    <h4>
        <span class="pull-right label label-primary">Data : @Model.data</span>
    </h4>
    <br>

    <br>
</div>

Front-end/Views/Shared/FilmPartial.cshtml
@model GestiuneFilme.Domain.Entitities.Film




<div class="well">



    @{
        var base64 = Convert.ToBase64String(Model.imageFilm);
        var imgSrc = String.Format("data:image/gif;base64,{0}", base64);
    }

    <div class="container">
       
    </div>

    <div class="top-left">
        <div class="col-md-3" style="padding-left: 40px;  padding-right: 30px;">
            <img src=@imgSrc class="img-responsive">
        </div>
        <h3><strong> @Model.titlu </strong> </h3>

        <h4>Regia: @Model.regia</h4>
        <h4>Distributia: @Model.distributia</h4>
        <h4>Numar Bilete: @Model.numarBilete</h4>



        <br>
        <br>


        <h4>
            <span class=" label label-primary">Data Premiera: @Model.dataPremiera.Date.ToString("d")</span>
            <br>

            <br>
            <span class="label label-primary">Data Difuzare: @Model.dataDifuzare.Date.ToString("d")</span>
        </h4>
        <br>

        <br>
    </div>





</div>

Front-end/Views/Shared/FilmPartialCumparator.cshtml
@model GestiuneFilme.Domain.Entitities.Film


<div class="well">



    @{
        var base64 = Convert.ToBase64String(Model.imageFilm);
        var imgSrc = String.Format("data:image/gif;base64,{0}", base64);
    }

    <div class="container">

    </div>

    <div class="top-left">

        <div class="col-md-3" style="padding-left: 40px;  padding-right: 30px;">
            <img src=@imgSrc class="img-responsive">
        </div>
        <h3><strong> @Model.titlu </strong> </h3>

        <h4>Regia: @Model.regia</h4>
        <h4>Distributia: @Model.distributia</h4>
        <h4>Numar Bilete: @Model.numarBilete</h4>

     

        @using (Html.BeginForm("RezervareBilete", "Cumparator", new { bilet = @Model, titluFilm = @Model.titlu }))
        {
            <p style="padding-left: 70%">
                <input type="submit"
                       class="btn-lg btn-success col-xs-pull-6"
                       value="Rezervare Film" />
            </p>
        }


        <h4>
            <span class=" label label-primary">Data Premiera: @Model.dataPremiera.Date.ToString("d")</span>
            <br>

            <br>
            <span class="label label-primary">Data Difuzare: @Model.dataDifuzare.Date.ToString("d")</span>
        </h4>
        <br>

        <br>

    </div>

</div>

Front-end/Views/Shared/RezervareBileteFinal.cshtml
@model GestiuneFilme.Domain.Entitities.Film



<div class="well">

    @{
        var base64 = Convert.ToBase64String(Model.imageFilm);
        var imgSrc = String.Format("data:image/gif;base64,{0}", base64);
    }

    <div class="container">

    </div>

    <div class="top-right">

        <div class="col-md-3" style="padding-left: 40px;  padding-right: 30px;">
            <img src=@imgSrc class="img-responsive">
        </div>
        <h3><strong> @Model.titlu </strong> </h3>

        <h4>Regia: @Model.regia</h4>
        <h4>Distributia: @Model.distributia</h4>
        <h4>Numar Bilete: @Model.numarBilete</h4>

        <h4>
            <span class=" label label-primary">Data Premiera: @Model.dataPremiera.Date.ToString("d")</span>
            <br>

            <br>
            <span class="label label-primary">Data Difuzare: @Model.dataDifuzare.Date.ToString("d")</span>
        </h4>
        <br>

        <br>

    </div>

</div>

Front-end/Views/Shared/_AdminLayout.cshtml
@{
    Layout = null;
}
<!DOCTYPE html>
<head>
    <meta name="viewport" content="width=device-width" />
    <link href="~/Content/bootstrap.css" rel="stylesheet" />
    <link href="~/Content/bootstrap-theme.css" rel="stylesheet" />
    <title></title>
</head>
<body>
    <div>
        @if (TempData["message"] != null)
    {
        <div class="alert alert-success">@TempData["message"]</div>
    }
        @{
        var userName = HttpContext.Current.User.Identity.Name;

    if (userName != "")
    {
        <h3>
            @Html.ActionLink("Online Movie Rental", "ListFilme", "Admin")
            <span class="btn-info btn pull-right">
                @Html.ActionLink(HttpContext.Current.User.Identity.Name + "-Logout", "Logout", "Account")
            </span>
        </h3>
    }
        }

        @RenderBody()
    </div>
</body>

Front-end/Views/Shared/_AngajatLayout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <link href="~/Content/bootstrap.css" rel="stylesheet" />
    <link href="~/Content/bootstrap-theme.css" rel="stylesheet" />
    <title></title>
</head>
<body>
    <div>
        @if (TempData["message"] != null)
        {

            <div class="alerg alert-success">@TempData["message"]</div>

        }
        @{
            var userName = HttpContext.Current.User.Identity.Name;
            if (userName != "")
            {
                <h3>
                    @Html.ActionLink("Online Movie Rental", "ListBilete", "Angajat")
                    <span class="btn-info btn pull-right">
                        @Html.ActionLink(HttpContext.Current.User.Identity.Name + " -Logout", "Logout", "Account")
                    </span>
                </h3>
            }
        }
        @RenderBody()
    </div>
</body>
</html>

Front-end/Views/Shared/_CumparatorLayout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <link href="~/Content/bootstrap.css" rel="stylesheet" />
    <link href="~/Content/bootstrap-theme.css" rel="stylesheet" />
    <title></title>
</head>
<body>
    <div>
        @if (TempData["message"] != null)
        {

            <div class="alerg alert-success">@TempData["message"]</div>

        }
        @{
            var userName = HttpContext.Current.User.Identity.Name;
            if (userName != "")
            {
                <h3>
                    @Html.ActionLink("Online Movie Rental", "ListFilme", "Cumparator")
                    <span class="btn-info btn pull-right">
                        @Html.ActionLink(HttpContext.Current.User.Identity.Name + " -Logout", "Logout", "Account")
                    </span>
                </h3>
            }
        }
        @RenderBody()
    </div>
</body>
</html>

Front-end/Views/Shared/_Layout.cshtml
<!DOCTYPE html>


<html>

<head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>@ViewBag.Title - Online Movie Rental</title>
        <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" media="screen" />
        <link href="~/Content/bootstrap-theme.min.css" rel="stylesheet" type="text/css" media="screen" />
</head>
   <body>

        <div class="navbar navbar-inverse" role="navigation">
            <a class="navbar-brand" href="#">Online Movie Rental</a>
        </div>
        <div class="row panel ">
            <div class="col-lg-3 ">

            </div>
            @RenderBody()

        </div>

    </body>

</html>